name: Auto-merge inactive entries
on:
  pull_request:
    types: [labeled, synchronize]
    paths: [ 'registry.json', 'entries/*.json' ]
jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i ajv ajv-formats
      - name: Build registry (entries mode)
        if: hashFiles('entries/*.json') != ''
        run: node tools/merge_entries.mjs
      - name: Schema check
        run: node ai-manifest-kit/scripts/validate-registry.mjs --file registry.json --out _reports/registry_validate.json
      - name: Ensure added/changed lines do not set status to active
        run: |
          git fetch origin "${{ github.event.pull_request.base.ref }}"
          git diff --unified=0 origin/${{ github.event.pull_request.base.ref }}...HEAD -- registry.json entries/*.json | grep '^+' | grep -qi '"status": *"active"' && { echo "Found active status in additions"; exit 1; } || echo "OK inactive only"
      - name: Merge PR (squash)
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            });
