name: Registry Metrics (Nightly)
on:
  schedule:
    - cron: '17 2 * * *'  # UTC nightly
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install deps
        run: npm i ajv ajv-formats node-fetch@^3 https-proxy-agent socks-proxy-agent
      - name: Remote checks (active only)
        run: node tools/check_registry_remote.mjs registry.json
      - name: Build metrics
        run: node tools/metrics_from_reports.mjs --out _metrics/metrics.json
      - uses: actions/upload-artifact@v4
        with: { name: registry-metrics, path: _metrics/metrics.json }
      - name: Commit metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(metrics): update nightly registry metrics'
          file_pattern: '_metrics/metrics.json'
