name: Registry sort & duplicate check
on:
  pull_request:
    paths: [ 'registry.json' ]
jobs:
  sort-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Check order and duplicates
        run: node tools/sort_registry.mjs --check
